stack.exe:main.o pop.o view.o push.o
	gcc -o stack.exe main.o pop.o view.o push.o
main.o:main.c myheader.h
	gcc -c main.c
pop.o:pop.c myheader.h
	gcc -c pop.c
push.o:push.c myheader.h
	gcc -c push.c
view.o:view.c myheader.h
	gcc -c view.c 
